FROM python:3.11-slim-bookworm

WORKDIR /opt/aquila

COPY requirements-ui.txt ./requirements-ui.txt
RUN pip install --no-cache-dir -r requirements-ui.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "PCR_plot.py", "--server.port=8501", "--server.address=0.0.0.0"]
